#ifndef REVOLUTION_OS_MEMORY_MAP_H
#define REVOLUTION_OS_MEMORY_MAP_H

#define OS_ADDR_MEMORY_MAP_PART_1       0x0000
#define OS_ADDR_MEMORY_MAP_SIZE         0x0100

#define OS_ADDR_BOOT_INFO               0x0000

#define OS_ADDR_DB_INTERFACE            0x0040
#define OS_ADDR_DB_INTEGRATOR_HOOK      0x0060

#define OS_ADDR_CURRENT_CONTEXT_REAL    0x00C0

#define OS_ADDR_PREVIOUS_INTERRUPT      0x00C4
#define OS_ADDR_CURRENT_INTERRUPT       0x00C8

#define OS_ADDR_TV_VIDEO_FORMAT         0x00CC

#define OS_ADDR_AUDIO_RAM_LENGTH        0x00D0

#define OS_ADDR_CURRENT_CONTEXT         0x00D4
#define OS_ADDR_CURRENT_FPU_CONTEXT     0x00D8

#define OS_ADDR_ACTIVE_THREAD_QUEUE     0x00DC

#define OS_ADDR_CURRENT_THREAD          0x00E4

#define OS_ADDR_DEBUG_MONITOR_SIZE      0x00E8
#define OS_ADDR_DEBUG_MONITOR           0x00EC

#define OS_ADDR_SIMULATED_MEMORY_SIZE   0x00F0

#define OS_ADDR_BOOT_INFO_2             0x00F4

#define OS_ADDR_BUS_CLOCK_SPEED         0x00F8
#define OS_ADDR_CPU_CLOCK_SPEED         0x00FC

#define OS_ADDR_MEMORY_MAP_PART_2       0x3000

#define OS_ADDR_EXCEPTION_TABLE         0x3000

#define OS_ADDR_INTERRUPT_TABLE         0x3040

#define OS_ADDR_EXI_LAST_PROBES         0x30C0

#define OS_ADDR_LINK_MODULE_LIST        0x30C8
#define OS_ADDR_LINK_LAST_MODULE_LIST   0x30CC
#define OS_ADDR_LINK_STRING_TABLE       0x30D0

#define OS_ADDR_SYSTEM_TIME             0x30D8

#define OS_ADDR_PAD_WIRELESS_FIX_MODE   0x30E0
#define OS_ADDR_PAD_BUTTON              0x30E3
#define OS_ADDR_DEVICE_CODE             0x30E6
#define OS_ADDR_BI2_DEBUG_FLAG          0x30E8
#define OS_ADDR_BI2_PAD_SPEC            0x30E9

#define OS_ADDR_LAUNCH_EXEC_PARAMS      0x30F0

#define OS_ADDR_PHYSICAL_MEM1_SIZE      0x3100
#define OS_ADDR_SIMULATED_MEM1_SIZE     0x3104
#define OS_ADDR_AVAILABLE_MEM1_START    0x310C
#define OS_ADDR_AVAILABLE_MEM1_END      0x3110

#define OS_ADDR_PHYSICAL_MEM2_SIZE      0x3118
#define OS_ADDR_SIMULATED_MEM2_SIZE     0x311C
#define OS_ADDR_ACCESSIBLE_MEM2         0x3120
#define OS_ADDR_AVAILABLE_MEM2_START    0x3124
#define OS_ADDR_AVAILABLE_MEM2_END      0x3128

#define OS_ADDR_IPC_BUFFER_START        0x3130
#define OS_ADDR_IPC_BUFFER_END          0x3134

#define OS_ADDR_HOLLYWOOD_REVISION      0x3138

#define OS_ADDR_IOS_REVISION            0x3140
#define OS_ADDR_IOS_BUILD_DATE          0x3144
#define OS_ADDR_IOS_HEAP_START          0x3148
#define OS_ADDR_IOS_HEAP_END            0x314C

#define OS_ADDR_GDDR_VENDOR_CODE        0x3158

#define OS_ADDR_BOOT_PROGRAM_TARGET     0x315C
#define OS_ADDR_APP_LOADER_TARGET       0x315D
#define OS_ADDR_DEV_KIT_VERSION         0x315E

#define OS_ADDR_MIOS_SHUTDOWN_FLAG      0x3164

#define OS_ADDR_CURRENT_APP_NAME        0x3180
#define OS_ADDR_CURRENT_APP_TYPE        0x3184

#define OS_ADDR_LOCKED_APP_TYPE         0x3187
#define OS_ADDR_MINIMUM_IOS_VERSION     0x3188

#define OS_ADDR_NAND_TITLE_LAUNCH_CODE  0x318C
#define OS_ADDR_NAND_TITLE_RETURN_CODE  0x3190

#define OS_ADDR_BOOT_PART_TYPE          0x3194
#define OS_ADDR_BOOT_PART_OFFSET        0x3198

#endif // REVOLUTION_OS_MEMORY_MAP_H
