// These files are automatically generated.
#include "ipl_error_eng_bmg.inc"
#include "ipl_error_fra_bmg.inc"
#include "ipl_error_ger_bmg.inc"
#include "ipl_error_ita_bmg.inc"
#include "ipl_error_jpn_bmg.inc"
#include "ipl_error_ned_bmg.inc"
#include "ipl_error_spa_bmg.inc"
#include "ipl_error_kor_bmg.inc"
#include "ipl_error_chn_bmg.inc"
#include "fatalDlg_ash.inc"
