#ifndef REVOLUTION_WWW_OPERA_TYPES_H
#define REVOLUTION_WWW_OPERA_TYPES_H

/***  ENUMS  ***/

typedef enum WWWEvent {
     WWW_EVT_CURSOR_CHANGE = 0,
     WWW_EVT_WINDOW_CLOSE,
     WWW_EVT_WINDOW_NEW,
     WWW_EVT_WINDOW_REQUEST,
     WWW_EVT_AUTHENTICATION,
     WWW_EVT_URL_CHANGE,
     WWW_EVT_LOADING_START,
     WWW_EVT_LOADING_FINISHED,
     WWW_EVT_LOADING_PROGRESS,
     WWW_EVT_UPLOADING_START,
     WWW_EVT_UPLOADING_FINISHED,
     WWW_EVT_DOCUMENT_TITLE,
     WWW_EVT_DOCUMENT_SIZE,
     WWW_EVT_DOCUMENT_ICON,
     WWW_EVT_LINK_CLICKED,
     WWW_EVT_SECURITY_MODE,
     WWW_EVT_LINK_NAVIGATED,
     WWW_EVT_LINK_HOVER,
     WWW_EVT_UNKNOWN_18,
     WWW_EVT_UNKNOWN_19,
     WWW_EVT_UNKNOWN_20,
     WWW_EVT_UNKNOWN_21,
     WWW_EVT_UNKNOWN_PROTOCOL,
     WWW_EVT_UNKNOWN_23,
     WWW_EVT_DOWNLOAD,
     WWW_EVT_UNKNOWN_25,
     WWW_EVT_UNKNOWN_26,
     WWW_EVT_UNKNOWN_27,
     WWW_EVT_UNKNOWN_28,
     WWW_EVT_ERROR,
     WWW_EVT_IMECREATE,
     WWW_EVT_IMEMOVE,
     WWW_EVT_IMECANCEL,
     WWW_EVT_ASYNC_DIALOG,
     WWW_EVT_BLOCKING_DIALOG,
     WWW_EVT_OUT_OF_MEMORY,
     WWW_EVT_SOFT_OUT_OF_MEMORY,
     WWW_EVT_UNKNOWN_37,
     WWW_EVT_UNKNOWN_38,
     WWW_EVT_UNKNOWN_39,
     WWW_EVT_UNKNOWN_40,
     WWW_EVT_UNKNOWN_41,
     WWW_EVT_UNKNOWN_42,
     WWW_EVT_UNKNOWN_43,
     WWW_EVT_PROTOCOL_LOADING_START,
     WWW_EVT_EXISTS_HISTORY,
     WWW_EVT_EXTERNAL_ACTION,
     WWW_EVT_UNKNOWN_47,
     WWW_EVT_UNKNOWN_48,
     WWW_EVT_UNKNOWN_49,
     WWW_EVT_UNKNOWN_50,
     WWW_EVT_UNKNOWN_51,
     WWW_EVT_SCREEN_INVALID,
     WWW_EVT_FILTERED_URL
} WWWEvent;

/*** STRUCTS ***/

typedef struct WWWHandleWindow {
    /* TODO */
} WWWHandleWindow;

typedef struct WWWHandleEventData {
    /* TODO */
} WWWHandleEventData;

typedef struct WWWHandle {
    /* TODO */
} WWWHandle;

typedef struct WWWRect {
    int left;   // 0x00
    int top;    // 0x04
    int right;  // 0x08
    int botom;  // 0x0C
} WWWRect;

#endif // REVOLUTION_WWW_OPERA_TYPES_H
