#ifndef NHTTP_ERROR_H
#define NHTTP_ERROR_H

typedef enum NHTTPErr {
    NHTTP_ERROR_SYSTEM = -1,
    NHTTP_ERROR_NONE,
    NHTTP_ERROR_ALLOC,
    NHTTP_ERROR_TOOMANYREQ,
    NHTTP_ERROR_SOCKET,
    NHTTP_ERROR_DNS,
    NHTTP_ERROR_CONNECT,
    NHTTP_ERROR_BUFFULL,
    NHTTP_ERROR_HTTPPARSE,
    NHTTP_ERROR_CANCELED,
    NHTTP_ERROR_REVOLUTIONSDK,
    NHTTP_ERROR_REVOLUTIONWIFI,
    NHTTP_ERROR_UNKNOWN,
    NHTTP_ERROR_DNS_PROXY,
    NHTTP_ERROR_CONNECT_PROXY,
    NHTTP_ERROR_SSL,
    NHTTP_ERROR_BUSY,
    NHTTP_ERROR_SSL_ROOTCA,
    NHTTP_ERROR_SSL_CLIENTCERT,
    NHTTP_ERROR_MAX,
} NHTTPErr;

#endif  // NHTTP_ERROR_H
