#ifndef NHTTP_ERROR_H
#define NHTTP_ERROR_H

typedef enum NHTTPErr {
    NHTTP_ERROR_SYSTEM = -1,
    NHTTP_ERROR_NONE = 0,
    NHTTP_ERROR_ALLOC = 1,
    NHTTP_ERROR_TOOMANYREQ = 2,
    NHTTP_ERROR_SOCKET = 3,
    NHTTP_ERROR_DNS = 4,
    NHTTP_ERROR_CONNECT = 5,
    NHTTP_ERROR_BUFFULL = 6,
    NHTTP_ERROR_HTTPPARSE = 7,
    NHTTP_ERROR_CANCELED = 8,
    NHTTP_ERROR_REVOLUTIONSDK = 9,
    NHTTP_ERROR_REVOLUTIONWIFI = 10,
    NHTTP_ERROR_UNKNOWN = 11,
    NHTTP_ERROR_DNS_PROXY = 12,
    NHTTP_ERROR_CONNECT_PROXY = 13,
    NHTTP_ERROR_SSL = 14,
    NHTTP_ERROR_BUSY = 15,
    NHTTP_ERROR_SSL_ROOTCA = 16,
    NHTTP_ERROR_SSL_CLIENTCERT = 17,
    NHTTP_ERROR_MAX = 18,
} NHTTPErr;

#endif  // NHTTP_ERROR_H
