REVOEX_ASMROOT = $(REVOLUTION_EXT_ROOT)/$(ASSEMBLY_ROOT)
REVOEX_SRCROOT = $(REVOLUTION_EXT_ROOT)/$(SOURCE_ROOT)
REVOEX_OBJROOT = $(REVOLUTION_EXT_ROOT)/$(OBJECT_ROOT)
REVOEX_OUTROOT = $(REVOLUTION_EXT_ROOT)/$(BUILD_ROOT)
REVOEX_INCROOT = $(REVOLUTION_EXT_ROOT)/$(INCLUDE_ROOT)

include $(REVOLUTION_EXT_ROOT)/$(RULES_ROOT)/net/build.mak

RevoEX: $(NET_BIN_OUT)
clean_RevoEX:
	@echo Cleaning RevoEX...
	@rm -rf $(REVOEX_OUTROOT)


