#include <private/hollywood.h>

void enableLegacyDI() {
    ACRIOP_WRITE_REG32(HW_COMPAT, (ACRIOP_READ_REG32(HW_COMPAT) & 0xFFFFFFBF) | (1<<6));
    ACRIOP_WRITE_REG32(HW_AIPPROT, (ACRIOP_READ_REG32(HW_AIPPROT) & 0xFFFFFFEF) | (1<<4));
    ACRIOP_DEL_REG_F(HW_ARMIRQMASK, (1<<18));
}

void setVI1Cfg(u32 val) {
    ACRIOP_WRITE_REG32(HW_VI1CFG, (ACRIOP_READ_REG32(HW_VI1CFG) & 0xFFFDFFFF) | (val<<17));
}

void setVISolidClrYCol(u32 val) {
    ACRIOP_WRITE_REG32(HW_VISOLID, (ACRIOP_READ_REG32(HW_VISOLID) & 0xFFFF00FF) | (val<<8));
}

u32 getVISolidClrYCol() {
    return (u8)(ACRIOP_READ_REG32(HW_VISOLID)>>8);
}

#define ACR_IOP_ADDR (OS_BASE_UNCACHED + ACR_REG_ADDRESS + AHB_TRUSTED_OFFSET)

// These are not volatile writes...
void GPIOPPCInit() {
    *(u32*)(ACR_IOP_ADDR + HW_GPIOB_DIR) = 0xC320;
    *(u32*)(ACR_IOP_ADDR + HW_GPIOB_OUT) = 0xC000;
}

void EjectDisc() {
    ACRIOP_SET_REG_F(HW_GPIOB_OUT, (1<<HW_GPIOPIN_EJECT_DISC));
}
