object: 'build/inputs/base.43E.dtk'

symbols: 'config/43E/symbols.txt'
splits: 'config/43E/splits.txt'

ldscript_template: ldscript_ipl2.lcf

export_all: true
fill_gaps: false

# fix up bss nightmare from the generated dol
block_relocations:
    - target: .bss:0x811B1498
      end:    .bss:0x8132FFFF


