#ifndef PRIVATE_HOLLYWOOD_FLIPPER_AI_REGS_H
#define PRIVATE_HOLLYWOOD_FLIPPER_AI_REGS_H

#define AI_CONTROL  0x0000
#define AI_CONTROL_PSTAT        0
#define AI_CONTROL_AFR          1
#define AI_CONTROL_AIINTMSK     2
#define AI_CONTROL_AIINT        3
#define AI_CONTROL_AIINTVLD     4
#define AI_CONTROL_SCRESET      5
#define AI_CONTROL_SAMPLERATE   6

#define AI_VOLUME   0x0004
#define AI_AISCNT   0x0008
#define AI_AIIT     0x000C

#endif // PRIVATE_HOLLYWOOD_FLIPPER_AI_REGS_H
