object: 'build/inputs/base.43J.dtk'

symbols: 'config/43J/symbols.txt'
splits: 'config/43J/splits.txt'

ldscript_template: ldscript_ipl2.lcf

export_all: true
fill_gaps: false

# fix up bss nightmare from the generated dol
block_relocations:
    - target: .bss:0x811C10D8
      end:    .bss:0x8132FFFF


