name: Build

on:
  push:
  pull_request:

jobs:
  build:
    # This is a *private* build container.
    container: ghcr.io/koopthekoopa/wii-ipl-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [43U, 43E, 43J, 43K]

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /orig .

    # Build the project
    - name: Build
      run: |
        python configure.py --map --version ${{ matrix.version }} \
            --binutils /binutils --compilers /compilers
        ninja all_source build/${{ matrix.version }}/progress.json \
            build/${{ matrix.version }}/report.json

    # Upload map files
    - name: Upload map
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_maps
        path: build/${{ matrix.version }}/**/*.MAP

    # Upload progress report
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/report.json